### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adelphia** [huika/UMA#52] opened 2015-10-05 11:08 UTC
Hi. I'm new to UMA so I viewed the documentation (UMA_Manual.pdf) but it is so outdated; it relates to version UMA version 1.0.1.0R. Will there be an update any time soon as the UMA_Manual.pdf is deprecated as it stands.

**Comment by nkv123** [comment] 2016-01-23 00:54
I agree.

**Comment by SecretAnorak** [comment] 2016-03-31 07:28
Unfortunately being a community project, contributors focus on refining and improving the system and no-one wants to spend time on documentation. I did try to address this with a video tutorial series which you can find here: https://www.youtube.com/watch?v=XN0E1G2ylbs&list=PLkDHFObfS19wRJ9vvaDTwCe-zRPv9jI25

**Comment by Joen-UnLogick** [comment] 2016-05-13 15:28
duplicate of #9

**Closed by Joen-UnLogick** 2016-05-13 15:28 UTC
