### ISSUE TITLE
Generated DNA Slot Data not showing in 5.3

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#62] opened 2016-03-31 03:42 UTC
Hi.

I've tried importing a few packs to 5.3( from 5.1.2) and I seem to get missing DNA and Slot Data for the Generated.asset. It appears to be mostly on females. Tried with Body Retexture vol.1 and Facepack.

Several "Object reference not set to an instance of an object" errors

Images show Missing and correct Data, plus debug info:
![screenhunter_442 mar 30 23 37](https://cloud.githubusercontent.com/assets/12765338/14164822/0de90518-f6d1-11e5-8717-edca9d030cf1.jpg)
![screenhunter_443 mar 30 23 37](https://cloud.githubusercontent.com/assets/12765338/14164824/0df04d5a-f6d1-11e5-8f6e-68df79622efe.jpg)
![screenhunter_444 mar 30 23 37](https://cloud.githubusercontent.com/assets/12765338/14164823/0df03950-f6d1-11e5-9d4c-ebd9461f2dad.jpg)
![screenhunter_445 mar 30 23 41](https://cloud.githubusercontent.com/assets/12765338/14164825/0df646e2-f6d1-11e5-86cf-3aa3f925fd83.jpg)

**Comment by SecretAnorak** [comment] 2016-03-31 07:23
I have not seen this occur with fresh DNA. However, I have found that if you generate your helper code then change or remove a DNA value, regeneration does not remove references to the old DNA values, causing errors like this. I have had to manually strip old references out of "_Generated" files in order to get UMA back into a working state. Worse still, hitting "Generate Helper Code" brings all the old references back.

**Comment by Jaimi** [comment] 2016-03-31 15:19
I have duplicated this, and I believe it is related to the previous issue (disappearing materials). What is happening is that it is trying to construct the materials on the overlay asset, but the material is null.

The Material in this case is a PBR Material for the eyes. I had the same issues you were seeing when I imported the "UMA Bod Retexture" before I had imported the PBR package (the PBR package contains the PBR materials). 

If I have done this out of order, then the OverlayDataAssets and SlotDataAssets are already corrupted. To fix this, you have to import the PBR package, and then reimport the package with missing materials.

Since the problem is that the material is not being deserialized correctly, I can't tell you what material is missing. I can however, stop it from crashing and put up a notice that the material is missing so it doesn't look so ugly with all the error messages. I'll put some code in to do this.

I think it likely that we should merge the PBR package into the main package at some point so this doesn't affect people.

**Comment by Jaimi** [comment] 2016-03-31 15:51
I have cleaned up the errors, and gave an actual error message in the console when the material is missing. 

Example:

"Error: Materials are missing on Asset: Eye Overlay. Have you imported all the packages?"

Checked in a few places for the missing materials, to avoid all the obj ref errors.

**Closed by Jaimi** 2016-03-31 15:51 UTC
